### ISSUE TITLE
Memory leak detected.

### ISSUE THREAD

**Issue by pmiotto** [ikhsanalatsary/multer-sharp-s3#18]
Hi.
It seems that when uploading an image with multiple resizes causes memory leaks under a small load. I've performed a load test using this library and it fails around 15 concurrent requests. Here's the error stack. Any help would be appreciated.

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:247:17)
    at Sharp.addListener (events.js:263:10)
    at Sharp.Readable.on (_stream_readable.js:800:35)
    at ManagedUpload.send (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/aws-sdk/lib/s3/managed_upload.js:185:11)
    at /Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/aws-sdk/lib/util.js:798:25
    at new WrappedPromise (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at ManagedUpload.promise (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/aws-sdk/lib/util.js:797:14)
    at MergeMapSubscriber.sizes.pipe.operators_1.mergeMap [as project] (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/multer-sharp-s3/dist/main.js:113:52)
    at MergeMapSubscriber._tryNext (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
    at propagateAslWrapper (/Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/async-listener/index.js:504:23)
    at /Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/async-listener/glue.js:188:31
    at /Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/async-listener/index.js:541:70
    at /Users/miottop/Documents/wip/ripcurl.searchgps.services.node/node_modules/async-listener/glue.js:188:31

**Comment by ikhsanalatsary** [comment]
Hi @pmiotto thanks for reporting this. how to reproduce like that?

**Comment by pmiotto** [comment]
HI @ikhsanalatsary. I've got an endpoint which uploads an image and a couple of resizes to S3, you can use a tool like jMeter to perform a loadtest. It fails under 10 concurrent requests. Not only I get this memory leak but some images uploaded to S3 are 0kb.

**Comment by ikhsanalatsary** [comment]
@pmiotto could you share your JMeter configuration?

**Comment by ikhsanalatsary** [comment]
My configuration 
![Screen Shot 2019-05-20 at 10 41 59](https://user-images.githubusercontent.com/5897415/57995386-f8b49c00-7aeb-11e9-9d55-c158f4e40200.png)
and sometimes one image is still uploaded 0 Bytes but at least it reduces the total from previous

**Comment by mohmmadmoussa1988** [comment]
Hello Dear,

Any solution for this case ?

**Comment by Milad** [comment]
This is expected to happen because you have many unused variables. Start by eliminating the unused variables from your code.

**Comment by Milad** [comment]
main.ts after the fix

`import { from } from 'rxjs'
import { map, mergeMap, toArray } from 'rxjs/operators'
import * as sharp from 'sharp'
import { lookup } from 'mime-types'
import { ManagedUpload } from 'aws-sdk/lib/s3/managed_upload'
import { StorageEngine } from 'multer'
import { Request } from 'express'
import { S3 } from 'aws-sdk'
import getSharpOptions from './get-sharp-options'
import transformer from './transformer'
import defaultKey from './get-filename'
import { S3StorageOptions, SharpOptions } from './types'

export type EStream = {
  stream: NodeJS.ReadableStream & sharp.Sharp
}
export type EFile = Express.Multer.File &
  EStream &
  Partial<S3.Types.PutObjectRequest>
export type Info = Partial<
  Express.Multer.File &
    ManagedUpload.SendData &
    S3.Types.PutObjectRequest &
    sharp.OutputInfo
>
export interface S3Storage {
  opts: S3StorageOptions
  sharpOpts: SharpOptions
}
export class S3Storage implements StorageEngine {
  protected static defaultOptions = {
    ACL: process.env.AWS_ACL || 'public-read',
    Bucket: process.env.AWS_BUCKET || null,
    Key: defaultKey,
    multiple: false,
  }

  constructor(options: S3StorageOptions) {
    if (!options.s3) {
      throw new Error('You have to specify s3 for AWS S3 to work.')
    }

    this.opts = { ...S3Storage.defaultOptions, ...options }
    this.sharpOpts = getSharpOptions(options)

    if (!this.opts.Bucket) {
      throw new Error('You have to specify Bucket for AWS S3 to work.')
    }

    if (typeof this.opts.Key !== 'string') {
      if (typeof this.opts.Key !== 'function') {
        throw new TypeError(
          `Key must be a "string" or "function" or "undefined" but got ${typeof this
            .opts.Key}`
        )
      }
    }
  }

  public _handleFile(req: Request, file: EFile, cb: (error?: any, info?: Info) => void) {
    const { opts } = this
    const { mimetype, stream } = file
    const params = {
      Bucket: opts.Bucket,
      ACL: opts.ACL,
      CacheControl: opts.CacheControl,
      ContentType: opts.ContentType,
      Metadata: opts.Metadata,
      StorageClass: opts.StorageClass,
      ServerSideEncryption: opts.ServerSideEncryption,
      SSEKMSKeyId: opts.SSEKMSKeyId,
      Body: stream,
      Key: opts.Key,
    }
    if (typeof opts.Key === 'function') {
      opts.Key(req, file, (fileErr, Key) => {
        if (fileErr) {
          cb(fileErr)
          return
        }
        params.Key = Key

        if (mimetype.includes('image')) {
          this._uploadProcess(params, file, cb)
        } else {
          this._uploadNonImage(params, file, cb)
        }
      })
    } else {
      if (mimetype.includes('image')) {
        this._uploadProcess(params, file, cb)
      } else {
        this._uploadNonImage(params, file, cb)
      }
    }
  }

  public _removeFile(req: Request, file: Info, cb: (error: Error) => void) {
    this.opts.s3.deleteObject({ Bucket: file.Bucket, Key: file.Key }, cb)
  }

  private _uploadProcess(
    params: S3.Types.PutObjectRequest,
    file: EFile,
    cb: (error?: any, info?: Info) => void
  ) {
    const { opts, sharpOpts } = this
    let { stream, mimetype } = file
    const {
      ACL,
      ContentDisposition,
      ContentType: optsContentType,
      StorageClass,
      ServerSideEncryption,
      Metadata,
    } = opts
    if (opts.multiple && Array.isArray(opts.resize) && opts.resize.length > 0) {
      const sizes = from(opts.resize)
      sizes
        .pipe(
          map((size) => {
            const resizerStream = transformer(sharpOpts, size)
            if (size.suffix === 'original') {
              size.Body = stream.pipe(sharp())
            } else {
              size.Body = stream.pipe(resizerStream)
            }
            return size
          }),
          mergeMap((size) => {
            const meta = { stream: size.Body }
            const getMetaFromSharp = meta.stream.toBuffer({
              resolveWithObject: true,
            })
            return from(
              getMetaFromSharp.then((result) => {
                return {
                  ...size,
                  ...result.info,
                  ContentType: result.info.format,
                  currentSize: result.info.size,
                }
              })
            )
          }),
          mergeMap((size) => {
            const { Body, ContentType } = size
            let newParams = {
              ...params,
              Body,
              ContentType,
              Key: `${params.Key}-${size.suffix}`,
            }
            const upload = opts.s3.upload(newParams)
            let currentSize = { [size.suffix]: 0 }
            upload.on('httpUploadProgress', function(ev) {
              if (ev.total) {
                currentSize[size.suffix] = ev.total
              }
            })
            const upload$ = from(
              upload.promise().then((result) => {
                // tslint:disable-next-line
                const { ...rest } = size
                return {
                  ...result,
                  ...rest,
                  currentSize: size.currentSize || currentSize[size.suffix],
                }
              })
            )
            return upload$
          }),
          toArray()
        )
        .subscribe((res) => {
          const mapArrayToObject: { [k: string]: any } = res.reduce(
            (acc, curr) => {
              // tslint:disable-next-line
              const { suffix, ContentType, currentSize, ...rest } = curr
              acc[suffix] = {
                ACL,
                ContentDisposition,
                StorageClass,
                ServerSideEncryption,
                Metadata,
                ...rest,
                size: currentSize,
                ContentType: optsContentType || ContentType
              }
              mimetype = lookup(ContentType) || `image/${ContentType}`
              return acc
            }, {})

          mapArrayToObject.mimetype = mimetype
          cb(null, JSON.parse(JSON.stringify(mapArrayToObject)))
        }, cb)
    } else {
      let currentSize = 0
      const resizerStream = transformer(sharpOpts, sharpOpts.resize)
      let newParams = { ...params, Body: stream.pipe(resizerStream) }
      const meta = { stream: newParams.Body }
      const meta$ = from(
        meta.stream.toBuffer({
          resolveWithObject: true,
        })
      )
      meta$
        .pipe(
          map((metadata) => {
            newParams.ContentType = opts.ContentType || metadata.info.format
            return metadata
          }),
          mergeMap((metadata) => {
            const upload = opts.s3.upload(newParams)
            upload.on('httpUploadProgress', function(ev) {
              if (ev.total) {
                currentSize = ev.total
              }
            })
            const upload$ = from(
              upload.promise().then((res) => {
                return { ...res, ...metadata.info }
              })
            )
            return upload$
          })
        )
        .subscribe((result) => {
          // tslint:disable-next-line
          const { size, format, ...rest } = result
          const endRes = {
            ACL,
            ContentDisposition,
            StorageClass,
            ServerSideEncryption,
            Metadata,
            ...rest,
            size: currentSize || size,
            ContentType: opts.ContentType || format,
            mimetype: lookup(format) || `image/${format}`
          }
          cb(null, JSON.parse(JSON.stringify(endRes)))
        }, cb)
    }
  }

  private _uploadNonImage(
    params: S3.Types.PutObjectRequest,
    file: EFile,
    cb: (error?: any, info?: Info) => void
  ) {
    const { opts } = this
    const { mimetype } = file
    let currentSize = 0
    params.ContentType = params.ContentType || mimetype
    const upload = opts.s3.upload(params)
    upload.on('httpUploadProgress', function(ev) {
      if (ev.total) {
        currentSize = ev.total
      }
    })
    upload.promise().then((result) => {
      const endRes = {
        size: currentSize,
        ACL: opts.ACL,
        ContentType: opts.ContentType || mimetype,
        ContentDisposition: opts.ContentDisposition,
        StorageClass: opts.StorageClass,
        ServerSideEncryption: opts.ServerSideEncryption,
        Metadata: opts.Metadata,
        ...result,
      }
      cb(null, JSON.parse(JSON.stringify(endRes)))
    }, cb)
  }
}

function s3Storage(options: S3StorageOptions) {
  return new S3Storage(options)
}

export default s3Storage
`

**Comment by djuko** [comment]
I am also having this issue. It is because I am having a long resize set. Is there a way to do this in a way of asynchronous calls (Promisse.all or something like that) to relieve the EventEmitter ?

**Comment by djuko** [comment]
I have increased for now the event emitter with `require('events').EventEmitter.defaultMaxListeners = 40`, but this should be heavily avoided. I suggest we find a way to implement async await when uploading multiple images. I'll follow up on this if I find a way and let you guys know :)

**Comment by Milad** [comment]
Of course it can be promisified easily, and if not, then it should!

**Comment by djuko** [comment]
I agree it should be promisified. I'll take a look at the src code after working hours, it would be best to implement it there
